# Generated by Django 3.0.2 on 2020-05-01 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('syncomercial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto_Onix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50)),
                ('prefixo', models.CharField(max_length=40)),
                ('embalagem', models.CharField(max_length=4)),
                ('unidade', models.CharField(choices=[('KG', 'Kilos'), ('G', 'Gramas'), ('L', 'Litros'), ('ML', 'Mililitros'), ('CX', 'Caixa')], max_length=2)),
                ('volume', models.DecimalField(decimal_places=3, max_digits=7)),
                ('status', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cadastro Onix',
                'verbose_name_plural': '1.0 - Cadastro Onix',
                'ordering': ['prefixo', 'volume'],
            },
        ),
        migrations.CreateModel(
            name='Produto_Syngenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agicode', models.CharField(max_length=8)),
                ('familia', models.CharField(max_length=40)),
                ('descricao', models.CharField(max_length=50)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('produto_onix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='synprodutos.Produto_Onix')),
            ],
            options={
                'verbose_name': 'Cadastro Syngenta',
                'verbose_name_plural': '2.0 - Cadastro Syngenta',
                'ordering': ['descricao'],
            },
        ),
        migrations.CreateModel(
            name='Produto_Distribuidor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=10, null=True)),
                ('descricao', models.CharField(blank=True, max_length=80, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('distribuidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syncomercial.Distribuidor')),
                ('produto_onix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='synprodutos.Produto_Onix')),
            ],
            options={
                'verbose_name': 'Cadastro Distribuidor',
                'verbose_name_plural': '3.0 - Cadastro Distribuidor',
                'ordering': ['distribuidor__razao_social', 'descricao'],
            },
        ),
    ]
