# Generated by Django 3.0.2 on 2020-01-14 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('syncomercial', '0001_initial'),
        ('synprodutos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto_Distribuidor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('descricao', models.CharField(max_length=80)),
                ('distribuidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='syncomercial.Distribuidor')),
                ('produto_onix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='synprodutos.Produto_Onix')),
            ],
        ),
        migrations.DeleteModel(
            name='DePara_OnixDistribuidor',
        ),
    ]
